common: &shared
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  database: db/development.sqlite3
  <<: *shared

test:
  database: db/test.sqlite3
  <<: *shared

production:
  database: db/production.sqlite3
  <<: *shared
